"""add_indexes_to_grocery_category_seller_fields

Revision ID: 41ab5277874e
Revises: 85ef98a7301c
Create Date: 2026-08-12 15:36:20.798215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ab5277874e'
down_revision: Union[str, Sequence[str], None] = '85ef98a7301c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grocery_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_current_seller'), ['current_seller'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_current_seller'))
        batch_op.drop_index(batch_op.f('ix_grocery_category'))

    # ### end Alembic commands ###
