"""added grocery type to grocery item

Revision ID: 7cc4431cbb7f
Revises: b53f6db28ee8
Create Date: 2026-02-13 22:41:04.016709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc4431cbb7f'
down_revision: Union[str, Sequence[str], None] = 'b53f6db28ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('best_seller',
               existing_type=postgresql.ENUM('MEENA', 'SHWAPNO', 'LOCAL', 'COMILLA', name='seller'),
               nullable=False)
        batch_op.alter_column('best_price',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.alter_column('best_price',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('best_seller',
               existing_type=postgresql.ENUM('MEENA', 'SHWAPNO', 'LOCAL', 'COMILLA', name='seller'),
               nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
