"""add index on grocery type column

Revision ID: 85ef98a7301c
Revises: 5dc40e0c9376
Create Date: 2026-08-12 14:12:23.674506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ef98a7301c'
down_revision: Union[str, Sequence[str], None] = '5dc40e0c9376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grocery_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_type'))

    # ### end Alembic commands ###
