"""add best_seller and best_price columns

Revision ID: b53f6db28ee8
Revises: 4e98b7e766d0
Create Date: 2026-02-07 16:19:52.671562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53f6db28ee8'
down_revision: Union[str, Sequence[str], None] = '4e98b7e766d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_seller', sa.Enum('MEENA', 'SHWAPNO', 'LOCAL', 'COMILLA', 'DEFAULT', name='seller'), nullable=True))
        batch_op.add_column(sa.Column('best_price', sa.Float(precision=2), nullable=True))
        batch_op.alter_column('current_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('best_price')
        batch_op.drop_column('best_seller')

    # ### end Alembic commands ###
